//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alanta.Client.UI.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alanta.Client.UI.Common.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Talk.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customer is waiting to talk to you.
        /// </summary>
        public static string AccessRequested {
            get {
                return ResourceManager.GetString("AccessRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Document.
        /// </summary>
        public static string AddDocument {
            get {
                return ResourceManager.GetString("AddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Screen.
        /// </summary>
        public static string AddScreen {
            get {
                return ResourceManager.GetString("AddScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Statistics Viewer.
        /// </summary>
        public static string AddStatisticsViewer {
            get {
                return ResourceManager.GetString("AddStatisticsViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Website.
        /// </summary>
        public static string AddWebsite {
            get {
                return ResourceManager.GetString("AddWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Whiteboard.
        /// </summary>
        public static string AddWhiteboard {
            get {
                return ResourceManager.GetString("AddWhiteboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room administrator has left the chat..
        /// </summary>
        public static string AdministratorLeftChat {
            get {
                return ResourceManager.GetString("AdministratorLeftChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room administrator is online, and you can send him or her a message via Alanta.
        /// </summary>
        public static string AdministratorOnlineCanSendMsg {
            get {
                return ResourceManager.GetString("AdministratorOnlineCanSendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages deleted.
        /// </summary>
        public static string AllMessagesDeleted {
            get {
                return ResourceManager.GetString("AllMessagesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one option need select.
        /// </summary>
        public static string AtLeastOneOptionNeedSelect {
            get {
                return ResourceManager.GetString("AtLeastOneOptionNeedSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image you selected is too large..
        /// </summary>
        public static string AvatarIsTooBig {
            get {
                return ResourceManager.GetString("AvatarIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication faulted.
        /// </summary>
        public static string CommunicationFaulted {
            get {
                return ResourceManager.GetString("CommunicationFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ConfirmBoxTitle {
            get {
                return ResourceManager.GetString("ConfirmBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation does not match the password.
        /// </summary>
        public static string ConfirmPasswordFailed {
            get {
                return ResourceManager.GetString("ConfirmPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected:.
        /// </summary>
        public static string ConnectedColon {
            get {
                return ResourceManager.GetString("ConnectedColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling {0}.
        /// </summary>
        public static string ConnectingToDescriptionFormat {
            get {
                return ResourceManager.GetString("ConnectingToDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite a friend to this meeting via email.
        /// </summary>
        public static string ContactsToolTipEmail {
            get {
                return ResourceManager.GetString("ContactsToolTipEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string DefaultLower {
            get {
                return ResourceManager.GetString("DefaultLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultUpper {
            get {
                return ResourceManager.GetString("DefaultUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred deleting chat messages.
        /// </summary>
        public static string DeleteChatMessagesFailed {
            get {
                return ResourceManager.GetString("DeleteChatMessagesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected {0}?.
        /// </summary>
        public static string DeleteSelectedFormat {
            get {
                return ResourceManager.GetString("DeleteSelectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of VNC desktop sharing is already running, and only one instance at a time is supported..
        /// </summary>
        public static string DesktopSharing_AnotherInstanceRunned {
            get {
                return ResourceManager.GetString("DesktopSharing_AnotherInstanceRunned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t yet support sharing your desktop from {0}..
        /// </summary>
        public static string DesktopSharing_BrowserNotSupportedFormat {
            get {
                return ResourceManager.GetString("DesktopSharing_BrowserNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization is already in progress..
        /// </summary>
        public static string DesktopSharing_InitializationInProgress {
            get {
                return ResourceManager.GetString("DesktopSharing_InitializationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desktop sharing control appears to be installed, but for some unknown reason, we couldn&apos;t communicate with it..
        /// </summary>
        public static string DesktopSharing_NotInitialized {
            get {
                return ResourceManager.GetString("DesktopSharing_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desktop sharing control does not appear to be installed..
        /// </summary>
        public static string DesktopSharing_NotInstalled {
            get {
                return ResourceManager.GetString("DesktopSharing_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to create the ActiveX object required to share your desktop..
        /// </summary>
        public static string DesktopSharing_UnableToCreateObject {
            get {
                return ResourceManager.GetString("DesktopSharing_UnableToCreateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installed version of the desktop sharing control is obsolete; you will need to update it..
        /// </summary>
        public static string DesktopSharing_VersionIsObsolete {
            get {
                return ResourceManager.GetString("DesktopSharing_VersionIsObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desktop sharing control was created, but initialization failed..
        /// </summary>
        public static string DesktopSharing_VncCreatedInitFailed {
            get {
                return ResourceManager.GetString("DesktopSharing_VncCreatedInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desktop sharing control was not successfully created..
        /// </summary>
        public static string DesktopSharing_VncYetNotCreated {
            get {
                return ResourceManager.GetString("DesktopSharing_VncYetNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details:.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details don&apos;t exist.
        /// </summary>
        public static string DetailsNotExist {
            get {
                return ResourceManager.GetString("DetailsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Call.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish this call.
        /// </summary>
        public static string DisconnectToolTip {
            get {
                return ResourceManager.GetString("DisconnectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string EmailColon {
            get {
                return ResourceManager.GetString("EmailColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address does not appear to be valid.
        /// </summary>
        public static string EmailValidationFailed {
            get {
                return ResourceManager.GetString("EmailValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetVolume operation failed..
        /// </summary>
        public static string ErrorGetVolumeFailed {
            get {
                return ResourceManager.GetString("ErrorGetVolumeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local media controller is not available..
        /// </summary>
        public static string ErrorMediaControllerUnavailable {
            get {
                return ResourceManager.GetString("ErrorMediaControllerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessageBoxCaption {
            get {
                return ResourceManager.GetString("ErrorMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute operation failed..
        /// </summary>
        public static string ErrorMuteOperationFailed {
            get {
                return ResourceManager.GetString("ErrorMuteOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVolume operation failed..
        /// </summary>
        public static string ErrorSetVolumeFailed {
            get {
                return ResourceManager.GetString("ErrorSetVolumeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alanta application has run into a problem that we can&apos;t deal with automatically, specifically:.
        /// </summary>
        public static string ErrorView_Title {
            get {
                return ResourceManager.GetString("ErrorView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute operation failed..
        /// </summary>
        public static string ErroUnmuteOperationFailed {
            get {
                return ResourceManager.GetString("ErroUnmuteOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Facebook invitations requires additional permissions..
        /// </summary>
        public static string FacebookDeliveryPermissionsRequired {
            get {
                return ResourceManager.GetString("FacebookDeliveryPermissionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All.
        /// </summary>
        public static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get image from {0}.
        /// </summary>
        public static string GetImageFromFormat {
            get {
                return ResourceManager.GetString("GetImageFromFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Initialization {
            get {
                return ResourceManager.GetString("Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining.
        /// </summary>
        public static string Joining {
            get {
                return ResourceManager.GetString("Joining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Leave a Message.
        /// </summary>
        public static string LeaveMessage {
            get {
                return ResourceManager.GetString("LeaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your microphone does not appear to be capturing audio. Click .
        /// </summary>
        public static string LocalCamera_NoAudio {
            get {
                return ResourceManager.GetString("LocalCamera_NoAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your webcam and microphone do not appear to be capturing data. Click .
        /// </summary>
        public static string LocalCamera_NoAudioOrVideo {
            get {
                return ResourceManager.GetString("LocalCamera_NoAudioOrVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your webcam does not appear to be capturing video. Click .
        /// </summary>
        public static string LocalCamera_NoVideo {
            get {
                return ResourceManager.GetString("LocalCamera_NoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your microphone and webcam.
        /// </summary>
        public static string Media_ConfigureMicrophoneAndWebcam {
            get {
                return ResourceManager.GetString("Media_ConfigureMicrophoneAndWebcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide remote webcams.
        /// </summary>
        public static string Media_HideRemoteWebCams {
            get {
                return ResourceManager.GetString("Media_HideRemoteWebCams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute your microphone.
        /// </summary>
        public static string Media_MuteLocalAudio {
            get {
                return ResourceManager.GetString("Media_MuteLocalAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop broadcasting your webcam.
        /// </summary>
        public static string Media_MuteLocalVideo {
            get {
                return ResourceManager.GetString("Media_MuteLocalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute room audio.
        /// </summary>
        public static string Media_MuteRoomAudio {
            get {
                return ResourceManager.GetString("Media_MuteRoomAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, no microphone was available..
        /// </summary>
        public static string Media_NoAudioDevice {
            get {
                return ResourceManager.GetString("Media_NoAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, we don&apos;t support any of the audio formats provided by your microphone..
        /// </summary>
        public static string Media_NoAudioFormat {
            get {
                return ResourceManager.GetString("Media_NoAudioFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, no webcam was available..
        /// </summary>
        public static string Media_NoVideoDevice {
            get {
                return ResourceManager.GetString("Media_NoVideoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, we don&apos;t support any of the video formats provided by your webcam..
        /// </summary>
        public static string Media_NoVideoFormat {
            get {
                return ResourceManager.GetString("Media_NoVideoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the volume of your microphone.
        /// </summary>
        public static string Media_SetMicrophoneVolume {
            get {
                return ResourceManager.GetString("Media_SetMicrophoneVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set room volume.
        /// </summary>
        public static string Media_SetRoomVolume {
            get {
                return ResourceManager.GetString("Media_SetRoomVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show remote webcams.
        /// </summary>
        public static string Media_ShowRemoteWebCams {
            get {
                return ResourceManager.GetString("Media_ShowRemoteWebCams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the media server..
        /// </summary>
        public static string Media_UnableToConnectToMediaServer {
            get {
                return ResourceManager.GetString("Media_UnableToConnectToMediaServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute your microphone.
        /// </summary>
        public static string Media_UnmuteLocalAudio {
            get {
                return ResourceManager.GetString("Media_UnmuteLocalAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start broadcasting your webcam.
        /// </summary>
        public static string Media_UnmuteLocalVideo {
            get {
                return ResourceManager.GetString("Media_UnmuteLocalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute room audio.
        /// </summary>
        public static string Media_UnmuteRoomAudio {
            get {
                return ResourceManager.GetString("Media_UnmuteRoomAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for someone to join....
        /// </summary>
        public static string Media_WaitingForSomeoneToJoin {
            get {
                return ResourceManager.GetString("Media_WaitingForSomeoneToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string MessageColon {
            get {
                return ResourceManager.GetString("MessageColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone muted.
        /// </summary>
        public static string MicrophoneMuted {
            get {
                return ResourceManager.GetString("MicrophoneMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed call.
        /// </summary>
        public static string MissedCall {
            get {
                return ResourceManager.GetString("MissedCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed call at {0}.
        /// </summary>
        public static string MissedCallFormat {
            get {
                return ResourceManager.GetString("MissedCallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to room {0} denied.
        /// </summary>
        public static string ModerationRequestDeniedFormat {
            get {
                return ResourceManager.GetString("ModerationRequestDeniedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameColon {
            get {
                return ResourceManager.GetString("NameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt to navigate to a new page failed..
        /// </summary>
        public static string NavigationFailed {
            get {
                return ResourceManager.GetString("NavigationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        public static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chat messages yet.
        /// </summary>
        public static string NoChatMessagesYet {
            get {
                return ResourceManager.GetString("NoChatMessagesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spaces.
        /// </summary>
        public static string NoSpaces {
            get {
                return ResourceManager.GetString("NoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, it&apos;s not work yet.
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occure error. Try again..
        /// </summary>
        public static string OccuredErrorTryAgain {
            get {
                return ResourceManager.GetString("OccuredErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to delete chat messages. Please contact the room owner..
        /// </summary>
        public static string PermissionErrorForDelMsgs {
            get {
                return ResourceManager.GetString("PermissionErrorForDelMsgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number:.
        /// </summary>
        public static string PhoneNumberColon {
            get {
                return ResourceManager.GetString("PhoneNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication faulted and your invitation expired. Reconnect?.
        /// </summary>
        public static string ReconnectOnCommunicationFaulted {
            get {
                return ResourceManager.GetString("ReconnectOnCommunicationFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason, certain parts of the room failed to load first time around. We&apos;ve reloaded them. Carry on..
        /// </summary>
        public static string RejoinOnValidationLoadedRoomFailed {
            get {
                return ResourceManager.GetString("RejoinOnValidationLoadedRoomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote videos muted.
        /// </summary>
        public static string RemoteVideoMuted {
            get {
                return ResourceManager.GetString("RemoteVideoMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} room of {1} was not found.
        /// </summary>
        public static string RoomNameAndOwnerNotFoundFormat {
            get {
                return ResourceManager.GetString("RoomNameAndOwnerNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified room does not appear to exist..
        /// </summary>
        public static string RoomNotFound {
            get {
                return ResourceManager.GetString("RoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Page .
        /// </summary>
        public static string RoomTitleEmpty {
            get {
                return ResourceManager.GetString("RoomTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default room of {0} .
        /// </summary>
        public static string RoomTitleRegisteredDefault {
            get {
                return ResourceManager.GetString("RoomTitleRegisteredDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room {0} of {1} .
        /// </summary>
        public static string RoomTitleRegisteredSpecified {
            get {
                return ResourceManager.GetString("RoomTitleRegisteredSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room unavailable.
        /// </summary>
        public static string RoomUnavailable {
            get {
                return ResourceManager.GetString("RoomUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, this is {0}. I&apos;m very sorry, but I&apos;m not available at the moment. Please leave me a message and the preferred method and time to contact you..
        /// </summary>
        public static string RoomUnavailableDefaultNoteFormat {
            get {
                return ResourceManager.GetString("RoomUnavailableDefaultNoteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Personal Image.
        /// </summary>
        public static string SelectAvatar {
            get {
                return ResourceManager.GetString("SelectAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send error information.
        /// </summary>
        public static string SendErrorInfo {
            get {
                return ResourceManager.GetString("SendErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Tell us more about what you were doing:.
        /// </summary>
        public static string SendErrorNoteLabel {
            get {
                return ResourceManager.GetString("SendErrorNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred processing a message from the server: {0}.  The error has been logged, and we&apos;ll try to get it fixed..
        /// </summary>
        public static string ServerMessageProcessingGenericError {
            get {
                return ResourceManager.GetString("ServerMessageProcessingGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred processing a message from the server: {0} \r\nThe error has been logged, and we&apos;ll try to get it fixed..
        /// </summary>
        public static string ServerMessageProcessingGenericError1 {
            get {
                return ResourceManager.GetString("ServerMessageProcessingGenericError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired..
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Focus.
        /// </summary>
        public static string SetFocus {
            get {
                return ResourceManager.GetString("SetFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users will be navigated to this window.
        /// </summary>
        public static string SetFocusDescription {
            get {
                return ResourceManager.GetString("SetFocusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Desktop.
        /// </summary>
        public static string SharedDesktop {
            get {
                return ResourceManager.GetString("SharedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred registering your shared desktop: {0}.
        /// </summary>
        public static string SharedDesktop_FailedToRegister {
            get {
                return ResourceManager.GetString("SharedDesktop_FailedToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred sharing your deskop.  This might have been caused by a failure to connect to the proxy server.  The actual message was: {0}.
        /// </summary>
        public static string SharedDesktop_FailedToShare {
            get {
                return ResourceManager.GetString("SharedDesktop_FailedToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred unregistering your shared desktop: {0}.
        /// </summary>
        public static string SharedDesktop_FailedToUnregister {
            get {
                return ResourceManager.GetString("SharedDesktop_FailedToUnregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Desktop Sharing Control.
        /// </summary>
        public static string SharedDesktop_InstallLink {
            get {
                return ResourceManager.GetString("SharedDesktop_InstallLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To share your desktop, you&apos;ll first need to install a small control.  Click this button to download the setup file, then follow your browser&apos;s instructions. (You may need to restart your browser when the installation is finished.).
        /// </summary>
        public static string SharedDesktop_InstallMessage {
            get {
                return ResourceManager.GetString("SharedDesktop_InstallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t installed the latest version of the Desktop Sharing Control ({0}). Your current installed version is {1}..
        /// </summary>
        public static string SharedDesktop_RecommendUpdateFormat {
            get {
                return ResourceManager.GetString("SharedDesktop_RecommendUpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop sharing reinitialized successfully. You can try again to start sharing desktop..
        /// </summary>
        public static string SharedDesktop_ReinitSucceed {
            get {
                return ResourceManager.GetString("SharedDesktop_ReinitSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Sharing Your Desktop.
        /// </summary>
        public static string SharedDesktop_StartSharingDesktop {
            get {
                return ResourceManager.GetString("SharedDesktop_StartSharingDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sharing Your Desktop.
        /// </summary>
        public static string SharedDesktop_StopSharingDesktop {
            get {
                return ResourceManager.GetString("SharedDesktop_StopSharingDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Desktop Sharing Control.
        /// </summary>
        public static string SharedDesktop_UpdateLink {
            get {
                return ResourceManager.GetString("SharedDesktop_UpdateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the Desktop Sharing Control that you have installed ({0}) is obsolete. Click the link below to update it to the latest version ({1}). You will unfortunately need to close your browser while the update is running..
        /// </summary>
        public static string SharedDesktop_UpdateMsgFormat {
            get {
                return ResourceManager.GetString("SharedDesktop_UpdateMsgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons, Silverlight doesn&apos;t let you open files in full-screen mode..
        /// </summary>
        public static string SharedFile_FullScreenNotSupportOpenFile {
            get {
                return ResourceManager.GetString("SharedFile_FullScreenNotSupportOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size is: .
        /// </summary>
        public static string SharedFile_MaximumFileSize {
            get {
                return ResourceManager.GetString("SharedFile_MaximumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wrong filter configuration was supplied..
        /// </summary>
        public static string SharedFile_WrongFileFilterConfig {
            get {
                return ResourceManager.GetString("SharedFile_WrongFileFilterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all messages.
        /// </summary>
        public static string ShowAllMessages {
            get {
                return ResourceManager.GetString("ShowAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers muted.
        /// </summary>
        public static string SpeakerMuted {
            get {
                return ResourceManager.GetString("SpeakerMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, this is {0}, and I&apos;m looking forward to talking with you. Before we do, let&apos;s make sure that we&apos;ll be able to hear each other. Start by clicking one of the buttons below. You should see a dialog box that confirms your choice. Just click &quot;OK&quot; in that dialog box, and we&apos;ll be off and running..
        /// </summary>
        public static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your Microphone.
        /// </summary>
        public static string StartMicrophone {
            get {
                return ResourceManager.GetString("StartMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your Webcam.
        /// </summary>
        public static string StartWebcam {
            get {
                return ResourceManager.GetString("StartWebcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Chat Only.
        /// </summary>
        public static string TextChatOnly {
            get {
                return ResourceManager.GetString("TextChatOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room is empty. Create a new item..
        /// </summary>
        public static string TipRoomEmpty {
            get {
                return ResourceManager.GetString("TipRoomEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too late, user left..
        /// </summary>
        public static string TooLateUserLeft {
            get {
                return ResourceManager.GetString("TooLateUserLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too long.
        /// </summary>
        public static string TooLong {
            get {
                return ResourceManager.GetString("TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short.
        /// </summary>
        public static string TooShort {
            get {
                return ResourceManager.GetString("TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer user.
        /// </summary>
        public static string TransferUser {
            get {
                return ResourceManager.GetString("TransferUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type something.
        /// </summary>
        public static string TypeSomething {
            get {
                return ResourceManager.GetString("TypeSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We weren&apos;t able to connect to our web service. In order to work, this application need access to a range of ports (943, and 4502-4534) that some firewalls may block. You will probably need to get in touch with your network administrator. See also: 
        ///
        ///http://msdn.microsoft.com/en-us/library/cc645032(VS.95).aspx
        ///http://blogs.msdn.com/b/ncl/archive/2009/06/23/why-does-silverlight-have-a-restricted-port-range-for-sockets.aspx
        ///
        ///Our apologies for the difficulty..
        /// </summary>
        public static string UnableConnectToWebService {
            get {
                return ResourceManager.GetString("UnableConnectToWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send chat message: .
        /// </summary>
        public static string UnableSendChatMsg {
            get {
                return ResourceManager.GetString("UnableSendChatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the audio server..
        /// </summary>
        public static string UnableToConnectToAudioServer {
            get {
                return ResourceManager.GetString("UnableToConnectToAudioServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload personal image..
        /// </summary>
        public static string UploadAvatarFailed {
            get {
                return ResourceManager.GetString("UploadAvatarFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId:.
        /// </summary>
        public static string UserIdAndColon {
            get {
                return ResourceManager.GetString("UserIdAndColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote user is not online. You can contact him or her via email..
        /// </summary>
        public static string UserOfflineContactViaEmail {
            get {
                return ResourceManager.GetString("UserOfflineContactViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote user is online, and you can send him or her a message via Alanta..
        /// </summary>
        public static string UserOnlineCanSendMessage {
            get {
                return ResourceManager.GetString("UserOnlineCanSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lost connection and successfully reconnected..
        /// </summary>
        public static string UserReconnectedFormat {
            get {
                return ResourceManager.GetString("UserReconnectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty.
        /// </summary>
        public static string ValidationFieldEmptyFormat {
            get {
                return ResourceManager.GetString("ValidationFieldEmptyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the errors on the form first..
        /// </summary>
        public static string ValidationFormFailed {
            get {
                return ResourceManager.GetString("ValidationFormFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen sharing error:.
        /// </summary>
        public static string VncError {
            get {
                return ResourceManager.GetString("VncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcamera muted.
        /// </summary>
        public static string WebcamMuted {
            get {
                return ResourceManager.GetString("WebcamMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whiteboard.
        /// </summary>
        public static string Whiteboard {
            get {
                return ResourceManager.GetString("Whiteboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify zoom level of the document.
        /// </summary>
        public static string ZoomDescription {
            get {
                return ResourceManager.GetString("ZoomDescription", resourceCulture);
            }
        }
    }
}
