//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alanta.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alanta.Common.ServerStrings", typeof(ServerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;border-width: medium; border-color: #C0C0C0&quot;&gt;
        ///&lt;b&gt;{0}&lt;/b&gt; has asked to talk to you in the room &lt;b&gt;&lt;a href=&quot;{1}&quot;&gt;{2}&lt;/a&gt;&lt;/b&gt;.&lt;br /&gt;
        ///
        ///&lt;b&gt;Details:&lt;/b&gt;&lt;br/&gt;
        ///Name: {0}&lt;br/&gt;
        ///Email: {1}&lt;br/&gt;
        ///Phone Number: {2}&lt;br/&gt;
        ///Message: {3}&lt;br/&gt;
        ///Location: {4}&lt;br/&gt;
        ///Source Url: {5}&lt;br/&gt;
        ///Room: {6}&lt;br/&gt;.
        /// </summary>
        public static string RequestAccessBodyHtmlFormat {
            get {
                return ResourceManager.GetString("RequestAccessBodyHtmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has asked to talk to you. The contact information provided is listed below:
        ///
        ///Details:
        ///Name: {0}
        ///Email: {1}
        ///Phone Number: {2}
        ///Message: {3}
        ///Location: {4}
        ///Source Url: {5}
        ///Room: {6}.
        /// </summary>
        public static string RequestAccessBodyTextFormat {
            get {
                return ResourceManager.GetString("RequestAccessBodyTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wants to talk to you.
        /// </summary>
        public static string RequestAccessSubjectFormat {
            get {
                return ResourceManager.GetString("RequestAccessSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///{1} is ready to talk to you.
        ///&lt;br /&gt;
        ///To begin talking, click here (or copy this url to your browser): &lt;a href=&quot;{3}&quot;&gt;{3}&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;hr&gt;
        ///Alanta.
        /// </summary>
        public static string RequestApprovedBodyHtmlFormat {
            get {
                return ResourceManager.GetString("RequestApprovedBodyHtmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} is ready to talk to you.
        ///To begin talking, click here (or copy this url to your browser): {3}.
        /// </summary>
        public static string RequestApprovedBodyTextFormat {
            get {
                return ResourceManager.GetString("RequestApprovedBodyTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is ready to talk to you.
        /// </summary>
        public static string RequestApprovedSubjectFormat {
            get {
                return ResourceManager.GetString("RequestApprovedSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///{0} has declined your request to talk.
        ///&lt;/div&gt;.
        /// </summary>
        public static string RequestDeniedBodyHtmlFormat {
            get {
                return ResourceManager.GetString("RequestDeniedBodyHtmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} declined your request to talk..
        /// </summary>
        public static string RequestDeniedBodyTextFormat {
            get {
                return ResourceManager.GetString("RequestDeniedBodyTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to talk to {0} was declined.
        /// </summary>
        public static string RequestDeniedSubjectFormat {
            get {
                return ResourceManager.GetString("RequestDeniedSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;border-width: medium; border-color: #C0C0C0&quot;&gt;
        ///&lt;b&gt;{0}&lt;/b&gt; was unable to get into the room &lt;b&gt;&lt;a href=&quot;{1}&quot;&gt;{2}&lt;/a&gt;&lt;/b&gt;, but has requested a follow-up with more information.&lt;br /&gt;
        ///&lt;b&gt;Details:&lt;/b&gt;&lt;br/&gt;
        ///Name: {0}&lt;br/&gt;
        ///Email: {3}&lt;br/&gt;
        ///Phone Number: {4}&lt;br/&gt;
        ///Message: {5}&lt;br/&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string RequestInfoBodyHtmlFormat {
            get {
                return ResourceManager.GetString("RequestInfoBodyHtmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was unable to get into the room {2}, but has requested a follow-up with more information.
        ///
        ///Details:
        ///Name: {0}
        ///Email: {3}
        ///Phone Number: {4}
        ///Message: {5}.
        /// </summary>
        public static string RequestInfoBodyTextFormat {
            get {
                return ResourceManager.GetString("RequestInfoBodyTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} asked for more information via room {1}.
        /// </summary>
        public static string RequestInfoSubjectFormat {
            get {
                return ResourceManager.GetString("RequestInfoSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body&gt;
        /// &lt;h2&gt;
        ///				{0}&lt;/h2&gt;
        ///		&lt;table&gt;
        ///				&lt;tr&gt;
        ///						&lt;td&gt;
        ///								When
        ///						&lt;/td&gt;
        ///						&lt;td&gt;
        ///								{2}
        ///						&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr&gt;
        ///						&lt;td&gt;
        ///								Will be?
        ///						&lt;/td&gt;
        ///						&lt;td&gt;
        ///								&lt;a href=&quot;{4}&quot;&gt;Yes&lt;/a&gt;&amp;nbsp; - &amp;nbsp;&lt;a href=&quot;{5}&quot;&gt;No&lt;/a&gt;&amp;nbsp; - &amp;nbsp;&lt;a href=&quot;{6}&quot;&gt;Maybe&lt;/a&gt;&amp;nbsp;&amp;nbsp;
        ///								&lt;a href=&quot;{7}&quot;&gt;Details&lt;/a&gt;
        ///						&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr&gt;
        ///						&lt;td&gt;
        ///								Who
        ///						&lt;/td&gt;
        ///						&lt;td&gt;
        ///								{3}
        ///						&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;
        ///		&lt;h4&gt;
        ///				{1}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ScheduleInvitationHtmlFormat {
            get {
                return ResourceManager.GetString("ScheduleInvitationHtmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The userid or password was incorrect..
        /// </summary>
        public static string UserIdOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("UserIdOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The userid or password was not found..
        /// </summary>
        public static string UserIdOrPasswordNotFound {
            get {
                return ResourceManager.GetString("UserIdOrPasswordNotFound", resourceCulture);
            }
        }
    }
}
